name: Test

on:
  push:
    branches:
      - ts
  workflow_dispatch:

permissions:
  contents: read

jobs:
  "test":
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - uses: pnpm/action-setup@v6
        with:
          version: 11
          cache: true
      - name: Test
        run: |
          npm run test
          npm run test:bdd
      - name: Build
        run: |
          npm run build
